### PR TITLE
[task2] upload to EC2 and get URL

### PR DESCRIPTION
**Pull request by autumn715219**
Dear PengPeng,
Please help to check my task of this week, thx :)
name : 邱媺涵
http://54.179.246.239:3000/api/attractions?page=1
[http://54.179.246.239:3000/api/attractions?page=0&keyword=藝文館所](http://54.179.246.239:3000/api/attractions?page=0&keyword=%E8%97%9D%E6%96%87%E9%A4%A8%E6%89%80)
[http://54.179.246.239:3000/api/attractions?page=0&keyword=北](http://54.179.246.239:3000/api/attractions?page=0&keyword=%E5%8C%97)
http://54.179.246.239:3000/api/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
You do not implement http://54.179.246.239:3000/api/categories API.

Complete it and re-request review.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Result is OK but it's much better to use `DISTINCT` in SQL query to list categories rather than get all and do it in your code.

Solve this issue and re-request review.

**Review by cwpeng — COMMENTED** [review]
I see no changes in your code.

**Comment by autumn715219** [comment]
Sorry, I just modified my code.
Please help me to check again, thx.

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
